import type React from "react";

/** Dark zinc + orange-500 palette for Cal.diy CSS custom properties. */
export const GBM_DARK_TOKENS: React.CSSProperties = {
  ["--cal-bg" as string]: "#09090b",
  ["--cal-bg-subtle" as string]: "#18181b",
  ["--cal-bg-muted" as string]: "#09090b",
  ["--cal-bg-emphasis" as string]: "#27272a",
  ["--cal-bg-inverted" as string]: "#fafafa",
  ["--cal-bg-primary" as string]: "#f97316",
  ["--cal-bg-primary-emphasis" as string]: "#ea580c",
  ["--cal-bg-primary-muted" as string]: "#18181b",
  ["--cal-brand" as string]: "#f97316",
  ["--cal-brand-emphasis" as string]: "#ea580c",
  ["--cal-brand-muted" as string]: "#431407",
  ["--cal-brand-subtle" as string]: "#7c2d12",
  ["--cal-brand-accent" as string]: "#ffffff",
  ["--cal-border" as string]: "#27272a",
  ["--cal-border-subtle" as string]: "#27272a",
  ["--cal-border-muted" as string]: "#18181b",
  ["--cal-border-emphasis" as string]: "#3f3f46",
  ["--cal-border-booker" as string]: "#27272a",
  ["--cal-text-emphasis" as string]: "#fafafa",
  ["--cal-text" as string]: "#d4d4d8",
  ["--cal-text-subtle" as string]: "#a1a1aa",
  ["--cal-text-muted" as string]: "#71717a",
  ["--cal-text-inverted" as string]: "#09090b",
  colorScheme: "dark",
};

/** Light zinc + orange-500 palette for Cal.diy CSS custom properties. */
export const GBM_LIGHT_TOKENS: React.CSSProperties = {
  ["--cal-bg" as string]: "#fafafa",
  ["--cal-bg-subtle" as string]: "#f4f4f5",
  ["--cal-bg-muted" as string]: "#fafafa",
  ["--cal-bg-emphasis" as string]: "#e4e4e7",
  ["--cal-bg-inverted" as string]: "#09090b",
  ["--cal-bg-primary" as string]: "#f97316",
  ["--cal-bg-primary-emphasis" as string]: "#ea580c",
  ["--cal-bg-primary-muted" as string]: "#fff7ed",
  ["--cal-brand" as string]: "#f97316",
  ["--cal-brand-emphasis" as string]: "#ea580c",
  ["--cal-brand-muted" as string]: "#fff7ed",
  ["--cal-brand-subtle" as string]: "#fed7aa",
  ["--cal-brand-accent" as string]: "#ffffff",
  ["--cal-border" as string]: "#e4e4e7",
  ["--cal-border-subtle" as string]: "#f4f4f5",
  ["--cal-border-muted" as string]: "#f4f4f5",
  ["--cal-border-emphasis" as string]: "#d4d4d8",
  ["--cal-border-booker" as string]: "#e4e4e7",
  ["--cal-text-emphasis" as string]: "#09090b",
  ["--cal-text" as string]: "#3f3f46",
  ["--cal-text-subtle" as string]: "#71717a",
  ["--cal-text-muted" as string]: "#a1a1aa",
  ["--cal-text-inverted" as string]: "#fafafa",
  colorScheme: "light",
};
